// <auto-generated />
using System;
using FactoryMonitoringWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FactoryMonitoringWeb.Migrations
{
    [DbContext(typeof(FactoryDbContext))]
    [Migration("20260203114505_RenameTimestampToDate")]
    partial class RenameTimestampToDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FactoryMonitoringWeb.Models.AgentCommand", b =>
                {
                    b.Property<int>("CommandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommandId"));

                    b.Property<string>("CommandData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExecutedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MCId")
                        .HasColumnType("int");

                    b.Property<string>("ResultData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CommandId");

                    b.HasIndex("MCId", "Status");

                    b.ToTable("AgentCommands");
                });

            modelBuilder.Entity("FactoryMonitoringWeb.Models.ConfigFile", b =>
                {
                    b.Property<int>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConfigId"));

                    b.Property<string>("ConfigContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("MCId")
                        .HasColumnType("int");

                    b.Property<bool>("PendingUpdate")
                        .HasColumnType("bit");

                    b.Property<bool>("UpdateApplied")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateRequestTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedContent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConfigId");

                    b.HasIndex("MCId")
                        .IsUnique();

                    b.HasIndex("PendingUpdate");

                    b.ToTable("ConfigFiles");
                });

            modelBuilder.Entity("FactoryMonitoringWeb.Models.FactoryMC", b =>
                {
                    b.Property<int>("MCId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MCId"));

                    b.Property<string>("ConfigFilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsApplicationRunning")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastHeartbeat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<string>("LogFolderPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LogStructureJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MCNumber")
                        .HasColumnType("int");

                    b.Property<string>("ModelFolderPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.HasKey("MCId");

                    b.HasIndex("IsOnline");

                    b.HasIndex("LineNumber");

                    b.HasIndex("LineNumber", "MCNumber")
                        .IsUnique();

                    b.ToTable("FactoryMCs");
                });

            modelBuilder.Entity("FactoryMonitoringWeb.Models.LineTargetModel", b =>
                {
                    b.Property<int>("LineTargetModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LineTargetModelId"));

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SetByUser")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("SetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TargetModelName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("LineTargetModelId");

                    b.ToTable("LineTargetModels");
                });

            modelBuilder.Entity("FactoryMonitoringWeb.Models.Model", b =>
                {
                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModelId"));

                    b.Property<DateTime>("DiscoveredDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCurrentModel")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUsed")
                        .HasColumnType("datetime2");

                    b.Property<int>("MCId")
                        .HasColumnType("int");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ModelPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ModelId");

                    b.HasIndex("MCId", "ModelName")
                        .IsUnique();

                    b.ToTable("Models");
                });

            modelBuilder.Entity("FactoryMonitoringWeb.Models.ModelDistribution", b =>
                {
                    b.Property<int>("DistributionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistributionId"));

                    b.Property<bool>("ApplyOnDownload")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DistributionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LineNumber")
                        .HasColumnType("int");

                    b.Property<int?>("MCId")
                        .HasColumnType("int");

                    b.Property<int>("ModelFileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("DistributionId");

                    b.HasIndex("MCId");

                    b.HasIndex("ModelFileId");

                    b.HasIndex("Status");

                    b.ToTable("ModelDistributions");
                });

            modelBuilder.Entity("FactoryMonitoringWeb.Models.ModelFile", b =>
                {
                    b.Property<int>("ModelFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModelFileId"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("FileData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("bit");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UploadedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ModelFileId");

                    b.ToTable("ModelFiles");
                });

            modelBuilder.Entity("FactoryMonitoringWeb.Models.SystemLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MCId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LogId");

                    b.HasIndex("MCId");

                    b.ToTable("SystemLogs");
                });

            modelBuilder.Entity("FactoryMonitoringWeb.Models.YieldRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("GoodCount")
                        .HasColumnType("int");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<int>("TotalCount")
                        .HasColumnType("int");

                    b.Property<string>("TrayId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("YieldPercentage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MachineId", "Date");

                    b.ToTable("YieldRecords");
                });

            modelBuilder.Entity("FactoryMonitoringWeb.Models.AgentCommand", b =>
                {
                    b.HasOne("FactoryMonitoringWeb.Models.FactoryMC", "FactoryMC")
                        .WithMany("Commands")
                        .HasForeignKey("MCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FactoryMC");
                });

            modelBuilder.Entity("FactoryMonitoringWeb.Models.ConfigFile", b =>
                {
                    b.HasOne("FactoryMonitoringWeb.Models.FactoryMC", "FactoryMC")
                        .WithOne("ConfigFile")
                        .HasForeignKey("FactoryMonitoringWeb.Models.ConfigFile", "MCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FactoryMC");
                });

            modelBuilder.Entity("FactoryMonitoringWeb.Models.Model", b =>
                {
                    b.HasOne("FactoryMonitoringWeb.Models.FactoryMC", "FactoryMC")
                        .WithMany("Models")
                        .HasForeignKey("MCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FactoryMC");
                });

            modelBuilder.Entity("FactoryMonitoringWeb.Models.ModelDistribution", b =>
                {
                    b.HasOne("FactoryMonitoringWeb.Models.FactoryMC", "FactoryMC")
                        .WithMany()
                        .HasForeignKey("MCId");

                    b.HasOne("FactoryMonitoringWeb.Models.ModelFile", "ModelFile")
                        .WithMany("ModelDistributions")
                        .HasForeignKey("ModelFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FactoryMC");

                    b.Navigation("ModelFile");
                });

            modelBuilder.Entity("FactoryMonitoringWeb.Models.SystemLog", b =>
                {
                    b.HasOne("FactoryMonitoringWeb.Models.FactoryMC", "FactoryMC")
                        .WithMany()
                        .HasForeignKey("MCId");

                    b.Navigation("FactoryMC");
                });

            modelBuilder.Entity("FactoryMonitoringWeb.Models.FactoryMC", b =>
                {
                    b.Navigation("Commands");

                    b.Navigation("ConfigFile");

                    b.Navigation("Models");
                });

            modelBuilder.Entity("FactoryMonitoringWeb.Models.ModelFile", b =>
                {
                    b.Navigation("ModelDistributions");
                });
#pragma warning restore 612, 618
        }
    }
}
